### ISSUE TITLE
Script fail on bootstrap

### ISSUE THREAD

**Issue by mscherer** [OSAS/ansible-role-ansible_bastion#1]
If there is nothing in the repo, it fail:

```
remote: fatal: Invalid revision range 0000000000000000000000000000000000000000..18e97bbfcd02b37780c3291ac92b371e239e4ad3
remote: Traceback (most recent call last):
remote:   File "/usr/local/bin/generate_ansible_command.py", line 162, in <module>
remote:     changed_files = get_changed_files(args.git, args.old, args.new)
remote:   File "/usr/local/bin/generate_ansible_command.py", line 143, in get_changed_files
remote:     "%s..%s" % (old, new)], cwd=git_repo)
remote:   File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
remote:     raise CalledProcessError(retcode, cmd, output=output)
remote: subprocess.CalledProcessError: Command '['git', '--no-pager', 'diff', '--name-status', '--diff-filter=ACDMR', '0000000000000000000000000000000000000000..18e97bbfcd02b37780c3291ac92b371e239e4ad3']' returned non-zero exit status 128
```

This should be filtered properly.

**Comment by mscherer** [comment]
Likely fixed by b86d0f2da0f915fb1805605e1e96c7a99e9f7034
